config/routes.rb
Rails.application.routes.draw do
  get 'attendances/attend'
  get 'attendances/show'
  devise_for :users

  # resources :attendances
  post 'create_attendance', to: 'attendances#create'
  delete 'destroy_attendance', to: 'attendances#destroy'
  # resources :attendances
  resources :events
  delete 'destroy_event', to: 'events#destroy'
  resources :profiles
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
  validates_presence_of :attendee_id, :attended_event_id
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past_events, -> { where('date < ?', Time.zone.now) }
  scope :future_events, -> { where('date > ?', Time.zone.now) }

  belongs_to :user
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendances, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  scope :attending_event, ->(event_id) { attendances.where(attended_event_id: event_id.exists?) }
  scope :past_events, ->(attending_event) { where('date < ?', Time.zone.now) }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :attendances, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendances, dependent: :destroy
  validates :email, :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: %i[login password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def create
    return unless Attendance.find_by(attendance_params).nil?

    @attendance = Attendance.new(attendance_params)
    @attendance.save
    redirect_to profile_path(current_user)
  end

  def destroy
    @attendance = Attendance.find_by(attendance_params)
    @attendance.destroy
    redirect_to profile_path(current_user)
    # flash.notice = 'you are no longer attending this event'
  end

  private

  def attendance_params
    params.permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.new
    @events = Event.all.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      redirect_to profile_path(current_user), notice: 'event has not been edited'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    flash.alert = if @event.destroy
                    'event deleted'
                  else
                    'event not deleted'
                  end
    redirect_to profile_path(current_user)
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    respond_to do |format|
      if @event.save
        format.turbo_stream
        redirect_to root_path
      else
        format.html do
          flash[:event_errors] = @event.errors.full_messages
          redirect_to root_path
        end
      end
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :location, :body)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def show
    @hosted_events = current_user.events.all
    @attending_events = current_user.attended_events.future_events
    @attended_events = current_user.attended_events.past_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_all_future.html.erb
<div class="card-title"><h3>Upcoming Events</h3></div>
<% @events.future_events.each do |event| %>
    <p class="event">
        <strong><%= link_to event.title, event, data: {turbo_frame: "_top"}, class: "title" %> </strong><br>
        Hosted by: <em>@<%= event.user.username %>,</em>&nbsp; <%= event.date %><br>
        Location: <em><%= event.location %></em><br>
        <%=  event.body %><br>
    </p>
<% end %>

app/views/events/_all_past.html.erb
<div class="card-title"><h3>Past Events</h3></div>
<% @events.past_events.each do |event| %>
    <p class="event">
        <strong> <%= link_to event.title, event, data: {turbo_frame: "_top"}, class: "title" %> </strong><br>
        Hosted by: <em>@<%= event.user.username %>,</em>&nbsp; <%= event.date %><br>
        Location: <em><%= event.location %></em><br>
        <%=  event.body %><br>
    </p>
<% end %>

app/views/events/_event.html.erb
<div>
    <p>
        <%= link_to event.title, event, data: {turbo_frame: "_top"} %><br>
        Date: <%= event.date %><br>
        Host: <%= event.user.username %><br>
        Location: <%= event.location %><br>
        Info: <%= event.body %><br>
        <%= link_to "edit", edit_event_path %>
        <%= link_to "delete", event_path(@event), data: { turbo_method: "delete", turbo_confirm: "click OK to delete event" }%>
        <%= link_to "attend event", attendances_attend_path(:attendee_id => current_user.id, :attended_event_id => @event.id), data: { turbo_method: "post" }%>
        <%= link_to "bail out", destroy_attendance_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), data: { turbo_method: "delete", turbo_confirm: "click OK to bail out of event" }%>
    </p>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event do |event| %>
    <% if event.object.errors.any? %>
    <%= pluralize(event.object.errors.count, "error") %>
    the following errors have prohibited this event from being saved:<br>
    <ul>
        <%= event.object.errors.each do |error| %>
        <li>
            <%= error.full_message %>
        </li>
        <% end %>
    </ul>
 <% end %>   
    <div class="card-title"><h3>Create new Event</h3></div>
    <div class="form-content">
    <%= event.text_area :title, placeholder: "title", class: "text-area" %><br>
    date: <%= event.date_field :date %><br>
    <%= event.text_area :location, placeholder: "location", class: "text-area" %><br>
    
    <%= event.text_area :body, placeholder: "message", class: "text-area" %><br>
    <%= event.submit "save event", class: "save"%><br>
<% end %>

app/views/events/create.turbo_stream.erb
<%= turbo_stream.prepend "events" do %>
<%= render "event", event: @event %>
<% end %>

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/index.html.erb
<% if user_signed_in? %>
    <div class="all-events">
    <div class="card">
        <%= render "form" %>
    </div>
    </div>
    <div class="upcoming-events">
    <div class="card">
        <%= render "all_future" %>
    </div>
    </div>
    <div class="past-events">
    <div class="card">
        <%= render "all_past" %>
    </div>
    </div>
    </div>
    
<% else %>
   <div class="messages">please log in :D</div>
<% end %>

app/views/events/show.html.erb
<div class="card-title"><h3><%= @event.title %></h3></div>
<div class="event-card">
    <div class="event-closeup">
    <p>
        Date: <%= @event.date %><br>
        Host: @<%= @event.user.username %><br>
        Location: <%= @event.location %><br>
        Info: <%= @event.body %><br>
        </p>
        <p>
        <% if user_signed_in? %>
            <% if @event.user_id == current_user.id %>
                <%= link_to "edit", edit_event_path, class: "event-button" %>
                <%= link_to "delete", event_path(@event), data: { turbo_method: "delete", turbo_confirm: "click OK to delete event" }, class: "event-button" %>
    
            <% elsif !current_user.attended_event_ids.include?(@event.id) %>
                <%= link_to "attend", create_attendance_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id), data: { turbo_method: "post" }, class: "event-button" %>

            <% else current_user.attended_event_ids.include?(@event.id) %>
                <%= link_to "bail out", destroy_attendance_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id), data: { turbo_method: "delete" }, class: "event-button" %>
            <% end %>
        <% end %>
  </p>
    </div>
    <p class="event-closeup">Attending:<br>
    <% @event.attendees.each do |attendee|%>
    <%= attendee.username %><br>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>


    <nav class="navbar">
      <div class="nav-container">
        <% if user_signed_in? %>
          
          <div class="nav-child1">
            <div class="nav-item" id="hover"> <%= link_to "EVENTS", root_path, class: "nav-item"%></div>
            <div class="nav-item" id="hover"> <%= link_to "MY EVENTS", profile_path(current_user), class: "nav-item"%></div>
          </div>
          <div class=nav-child2>
            <p>EVENT MANAGER</p>
          </div>
          <div class="nav-child3">
            <div class="nav-item" id="hover"> <%= link_to "LOG OUT", destroy_user_session_path, data: { turbo_method: "delete" }, class: "nav-item"%></div>
            <div class="nav-item"> @<%= current_user.username %> SIGNED IN</div>
          </div>
        <% else %>
          <div class="nav-item" id="hover"> <%= link_to "LOG IN", new_user_session_path, method: :get, class: "nav-item"%> </div>
          <div class="nav-item" id="hover"> <%= link_to "SIGN UP", new_user_registration_path, method: :get, class: "nav-item" %></div>
        <% end %>
      
  
    </nav>
    </div>
    <div class="messages">
 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>

  </body>
</html>

app/views/profiles/_attending.html.erb
<div class="card-title"><h3>Upcoming Events</h3></div>
<% @attending_events.each do |event| %>
    <p class="event">
        <strong><%= link_to event.title, event, data: {turbo_frame: "_top"}, class: "title"%></strong><br>
        Hosted by: <em>@<%= event.user.username %>,</em>&nbsp; <%= event.date %><br>
        Location: <em><%= event.location %></em><br>
        <%=  event.body %><br>
        
    </p>
<% end %>

app/views/profiles/_hosting.html.erb
<div class="card-title"><h3>Hosting</h3></div>
<% @hosted_events.each do |event| %>
  <p class="event">
      <strong><%= link_to event.title, event, data: {turbo_frame: "_top"}, class: "title" %></strong><br>
      <%= event.date %><br>
      Location: <em><%= event.location %></em><br>
      <%=  event.body %><br>
  </p>
<% end %>

app/views/profiles/_past.html.erb
<div class="card-title"><h3>Past Events</h3></div>
<% @attended_events.each do |event| %>
    <p class="event">
        <strong><%= link_to event.title, event, data: {turbo_frame: "_top"}, class: "title" %></strong><br>
        Hosted by: <em>@<%= event.user.username %>,</em>&nbsp; <%= event.date %><br>
        Location: <em><%= event.location %></em><br>
        <%=  event.body %><br>
        
    </p>
<% end %>

app/views/profiles/show.html.erb
<div class="all-events">
<div class="hosting-events">
    <%= render "hosting" %>
</div>
<div class="upcoming-events">
    <%= render "attending" %>
</div>
<div class="past-events">
<%= render "past" %>
</div>
</div>